package platform

import "time"

func RegisterDefaultProviders(r *Registry) {
	defaultTimeout := 30 * time.Second

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "cloudflare",
		Name:                "Cloudflare",
		Category:            CategoryDeveloper,
		Description:         "Cloudflare API for DNS, Workers, Pages, and Edge rules",
		BaseURL:             "https://api.cloudflare.com/client/v4",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_token"},
		SupportedOperations: []string{"list_zones", "dns_records", "workers", "purge_cache"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapRequestProxy, CapHealthCheck},
		WebsiteURL:          "https://www.cloudflare.com",
		DocsURL:             "https://developers.cloudflare.com/api/",
		APIReferenceURL:     "https://developers.cloudflare.com/api/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Generous free plan with unlimited DNS and 100k daily Worker requests.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "github",
		Name:                "GitHub",
		Category:            CategoryDeveloper,
		Description:         "GitHub REST and GraphQL APIs for repositories, actions, and issues",
		BaseURL:             "https://api.github.com",
		AuthType:            AuthTypePersonalToken,
		AuthHeaderName:      "Authorization",
		AuthHeaderPrefix:    "Bearer ",
		RequiredCredentials: []string{"personal_access_token"},
		SupportedOperations: []string{"get_repo", "list_issues", "trigger_workflow", "create_release"},
		Capabilities:        []Capability{CapPersonalToken, CapOAuth2, CapWebhook, CapResourceListing, CapPagination},
		WebsiteURL:          "https://github.com",
		DocsURL:             "https://docs.github.com/en/rest",
		APIReferenceURL:     "https://docs.github.com/en/rest",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier includes 5000 API requests per hour with personal access token.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "google-cloud",
		Name:                "Google Cloud",
		Category:            CategoryDeveloper,
		Description:         "Google Cloud Platform (GCP) APIs, Cloud Storage (GCS), and Cloud services",
		BaseURL:             "https://cloudresourcemanager.googleapis.com/v1",
		AuthType:            AuthTypeServiceAcct,
		RequiredCredentials: []string{"service_account_json"},
		SupportedOperations: []string{"storage_upload", "storage_download", "list_buckets", "iam_check"},
		Capabilities:        []Capability{CapServiceAccount, CapFileUpload, CapFileDownload, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://cloud.google.com",
		DocsURL:             "https://cloud.google.com/docs",
		APIReferenceURL:     "https://cloud.google.com/apis/docs/overview",
		FreeTierStatus:      "available",
		FreeTierNotes:       "$300 free credits for new accounts + always-free tier GCP services.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "vercel",
		Name:                "Vercel",
		Category:            CategoryDeveloper,
		Description:         "Vercel Deployment and Project API",
		BaseURL:             "https://api.vercel.com",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"bearer_token"},
		SupportedOperations: []string{"list_deployments", "create_deployment", "get_project"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://vercel.com",
		DocsURL:             "https://vercel.com/docs/rest-api",
		APIReferenceURL:     "https://vercel.com/docs/rest-api",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Hobby tier available for personal and non-commercial projects.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "supabase",
		Name:                "Supabase",
		Category:            CategoryDeveloper,
		Description:         "Supabase Management and Database API",
		BaseURL:             "https://api.supabase.com/v1",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"access_token"},
		SupportedOperations: []string{"list_projects", "get_project", "run_query"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://supabase.com",
		DocsURL:             "https://supabase.com/docs/reference/api/introduction",
		APIReferenceURL:     "https://supabase.com/docs/reference/api/introduction",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier includes 2 free projects, 500MB database, and 1GB storage.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "neon",
		Name:                "Neon Serverless Postgres",
		Category:            CategoryDeveloper,
		Description:         "Neon API for serverless Postgres branches and databases",
		BaseURL:             "https://console.neon.tech/api/v2",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"list_projects", "create_branch", "get_connection_uri"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://neon.tech",
		DocsURL:             "https://neon.tech/docs/reference/api-reference",
		APIReferenceURL:     "https://neon.tech/docs/reference/api-reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier includes 0.5 GiB storage and branching.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "resend",
		Name:                "Resend",
		Category:            CategoryComm,
		Description:         "Email delivery service for developers",
		BaseURL:             "https://api.resend.com",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"send_email", "get_email", "list_domains"},
		Capabilities:        []Capability{CapBearerAuth, CapHealthCheck, CapRequestProxy},
		WebsiteURL:          "https://resend.com",
		DocsURL:             "https://resend.com/docs/api-reference/introduction",
		APIReferenceURL:     "https://resend.com/docs/api-reference/emails/send-email",
		FreeTierStatus:      "available",
		FreeTierNotes:       "3,000 emails per month, 100 emails per day on free tier.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "sendgrid",
		Name:                "SendGrid",
		Category:            CategoryComm,
		Description:         "Twilio SendGrid Email API",
		BaseURL:             "https://api.sendgrid.com/v3",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"mail_send", "get_stats"},
		Capabilities:        []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:          "https://sendgrid.com",
		DocsURL:             "https://docs.sendgrid.com/api-reference",
		APIReferenceURL:     "https://docs.sendgrid.com/api-reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "100 emails per day free forever.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "twilio",
		Name:                "Twilio",
		Category:            CategoryComm,
		Description:         "Programmable SMS and Voice API",
		BaseURL:             "https://api.twilio.com/2010-04-01",
		AuthType:            AuthTypeBasicAuth,
		RequiredCredentials: []string{"account_sid", "auth_token"},
		SupportedOperations: []string{"send_sms", "make_call"},
		Capabilities:        []Capability{CapBasicAuth, CapWebhook, CapHealthCheck},
		WebsiteURL:          "https://www.twilio.com",
		DocsURL:             "https://www.twilio.com/docs/usage/api",
		APIReferenceURL:     "https://www.twilio.com/docs/usage/api",
		FreeTierStatus:      "trial",
		FreeTierNotes:       "Free trial credit provided upon initial account registration.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "discord",
		Name:                "Discord",
		Category:            CategoryComm,
		Description:         "Discord Bot API and Webhooks",
		BaseURL:             "https://discord.com/api/v10",
		AuthType:            AuthTypeBearerToken,
		AuthHeaderPrefix:    "Bot ",
		RequiredCredentials: []string{"bot_token"},
		SupportedOperations: []string{"create_message", "get_channel", "execute_webhook"},
		Capabilities:        []Capability{CapBearerAuth, CapWebhook, CapResourceListing},
		WebsiteURL:          "https://discord.com",
		DocsURL:             "https://discord.com/developers/docs/intro",
		APIReferenceURL:     "https://discord.com/developers/docs/reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free bot API with per-route rate limits.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "slack",
		Name:                "Slack",
		Category:            CategoryComm,
		Description:         "Slack Web API for messaging and channels",
		BaseURL:             "https://slack.com/api",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"bot_token"},
		SupportedOperations: []string{"chat.postMessage", "conversations.list"},
		Capabilities:        []Capability{CapBearerAuth, CapOAuth2, CapWebhook},
		WebsiteURL:          "https://slack.com",
		DocsURL:             "https://api.slack.com/web",
		APIReferenceURL:     "https://api.slack.com/methods",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier workspace allows custom apps and bot integrations.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "sentry",
		Name:                "Sentry",
		Category:            CategoryMonitoring,
		Description:         "Application error tracking and performance monitoring",
		BaseURL:             "https://sentry.io/api/0",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"auth_token"},
		SupportedOperations: []string{"list_issues", "get_issue", "list_projects"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://sentry.io",
		DocsURL:             "https://docs.sentry.io/api/",
		APIReferenceURL:     "https://docs.sentry.io/api/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Developer plan includes 5,000 errors per month free.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "betterstack",
		Name:                "Better Stack",
		Category:            CategoryMonitoring,
		Description:         "Uptime monitoring and incident management",
		BaseURL:             "https://uptime.betterstack.com/api/v2",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_token"},
		SupportedOperations: []string{"list_monitors", "create_monitor"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://betterstack.com",
		DocsURL:             "https://betterstack.com/docs/uptime/api/",
		APIReferenceURL:     "https://betterstack.com/docs/uptime/api/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free plan includes 10 monitors with 3-minute checks.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "webhook",
		Name:                "Generic Webhook",
		Category:            CategoryAutomation,
		Description:         "Outbound webhook delivery and payload dispatch",
		BaseURL:             "",
		AuthType:            AuthTypeCustomHeader,
		RequiredCredentials: []string{"target_url"},
		SupportedOperations: []string{"dispatch_event"},
		Capabilities:        []Capability{CapWebhook, CapSignedRequest},
		WebsiteURL:          "https://ekarouter.dev",
		DocsURL:             "https://ekarouter.dev/docs/webhooks",
		APIReferenceURL:     "https://ekarouter.dev/docs/webhooks",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Self-hosted within EkaRouter.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "firecrawl",
		Name:                "Firecrawl",
		Category:            CategoryScrapingData,
		Description:         "Web scraping and Markdown extraction for AI applications",
		BaseURL:             "https://api.firecrawl.dev/v1",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"scrape", "crawl", "map"},
		Capabilities:        []Capability{CapBearerAuth, CapHealthCheck, CapRequestProxy},
		WebsiteURL:          "https://firecrawl.dev",
		DocsURL:             "https://docs.firecrawl.dev",
		APIReferenceURL:     "https://docs.firecrawl.dev/api-reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "500 credits free tier available on sign-up.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "tavily",
		Name:                "Tavily Search API",
		Category:            CategoryScrapingData,
		Description:         "Search API optimized for LLMs and autonomous agents",
		BaseURL:             "https://api.tavily.com",
		AuthType:            AuthTypeAPIKeyHeader,
		AuthHeaderName:      "api-key",
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"search", "extract"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapHealthCheck},
		WebsiteURL:          "https://tavily.com",
		DocsURL:             "https://docs.tavily.com",
		APIReferenceURL:     "https://docs.tavily.com/api-reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "1,000 free searches per month.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "serpapi",
		Name:                "SerpAPI",
		Category:            CategoryScrapingData,
		Description:         "Real-time Google search results API",
		BaseURL:             "https://serpapi.com",
		AuthType:            AuthTypeCustomHeader,
		AuthHeaderName:      "Authorization",
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"search"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapHealthCheck},
		WebsiteURL:          "https://serpapi.com",
		DocsURL:             "https://serpapi.com/search-api",
		APIReferenceURL:     "https://serpapi.com/search-api",
		FreeTierStatus:      "available",
		FreeTierNotes:       "100 searches per month on free tier.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "jina",
		Name:                "Jina AI Reader",
		Category:            CategoryScrapingData,
		Description:         "Converts any URL or search query into clean Markdown",
		BaseURL:             "https://r.jina.ai",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"read_url", "search"},
		Capabilities:        []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:          "https://jina.ai",
		DocsURL:             "https://jina.ai/reader",
		APIReferenceURL:     "https://jina.ai/reader",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier with 1,000,000 tokens on registration.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "cloudflare-r2",
		Name:                "Cloudflare R2",
		Category:            CategoryStorage,
		Description:         "S3-compatible zero-egress object storage",
		BaseURL:             "https://api.cloudflare.com/client/v4",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_token", "account_id"},
		SupportedOperations: []string{"list_buckets", "get_bucket"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://developers.cloudflare.com/r2/",
		DocsURL:             "https://developers.cloudflare.com/r2/api/",
		APIReferenceURL:     "https://developers.cloudflare.com/r2/api/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "10 GB per month free storage with 10M Class B operations.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "stripe",
		Name:                "Stripe",
		Category:            CategoryPayments,
		Description:         "Online payment processing platform for internet businesses",
		BaseURL:             "https://api.stripe.com/v1",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"secret_key"},
		SupportedOperations: []string{"create_customer", "create_payment_intent", "list_charges"},
		Capabilities:        []Capability{CapBearerAuth, CapWebhook, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://stripe.com",
		DocsURL:             "https://stripe.com/docs/api",
		APIReferenceURL:     "https://stripe.com/docs/api",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Test mode is completely free with unlimited requests.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "midtrans",
		Name:                "Midtrans",
		Category:            CategoryPayments,
		Description:         "Indonesian and Southeast Asian payment gateway",
		BaseURL:             "https://api.midtrans.com/v2",
		AuthType:            AuthTypeBasicAuth,
		RequiredCredentials: []string{"server_key"},
		SupportedOperations: []string{"charge", "status", "cancel"},
		Capabilities:        []Capability{CapBasicAuth, CapWebhook, CapHealthCheck},
		WebsiteURL:          "https://midtrans.com",
		DocsURL:             "https://docs.midtrans.com",
		APIReferenceURL:     "https://docs.midtrans.com/reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free sandbox environment with full simulation support.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "posthog",
		Name:                "PostHog",
		Category:            CategoryAnalytics,
		Description:         "Product analytics, session recording, and feature flags",
		BaseURL:             "https://app.posthog.com/api",
		AuthType:            AuthTypePersonalToken,
		AuthHeaderName:      "Authorization",
		AuthHeaderPrefix:    "Bearer ",
		RequiredCredentials: []string{"personal_api_key"},
		SupportedOperations: []string{"capture_event", "list_cohorts"},
		Capabilities:        []Capability{CapPersonalToken, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://posthog.com",
		DocsURL:             "https://posthog.com/docs/api",
		APIReferenceURL:     "https://posthog.com/docs/api",
		FreeTierStatus:      "available",
		FreeTierNotes:       "1,000,000 events free every month.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "umami",
		Name:                "Umami",
		Category:            CategoryAnalytics,
		Description:         "Simple, privacy-friendly open-source web analytics",
		BaseURL:             "https://api.umami.is/v1",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"get_websites", "get_stats"},
		Capabilities:        []Capability{CapBearerAuth, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://umami.is",
		DocsURL:             "https://umami.is/docs/api",
		APIReferenceURL:     "https://umami.is/docs/api",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Umami Cloud has a free plan for up to 10k events/month.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "mapbox",
		Name:                "Mapbox",
		Category:            CategoryMaps,
		Description:         "Location data and developer mapping platform",
		BaseURL:             "https://api.mapbox.com",
		AuthType:            AuthTypeCustomHeader,
		RequiredCredentials: []string{"access_token"},
		SupportedOperations: []string{"geocoding", "directions", "static_map"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapHealthCheck},
		WebsiteURL:          "https://www.mapbox.com",
		DocsURL:             "https://docs.mapbox.com/api/",
		APIReferenceURL:     "https://docs.mapbox.com/api/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Generous free tier includes 50,000 free geocoding requests/month.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "virustotal",
		Name:                "VirusTotal",
		Category:            CategorySecurity,
		Description:         "Malware and URL intelligence analysis",
		BaseURL:             "https://www.virustotal.com/api/v3",
		AuthType:            AuthTypeAPIKeyHeader,
		AuthHeaderName:      "x-apikey",
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"get_ip_report", "get_domain_report", "get_file_report"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapHealthCheck},
		WebsiteURL:          "https://www.virustotal.com",
		DocsURL:             "https://docs.virustotal.com/reference/overview",
		APIReferenceURL:     "https://docs.virustotal.com/reference/overview",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Community API allows 4 requests per minute and 500 requests per day.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "abuseipdb",
		Name:                "AbuseIPDB",
		Category:            CategorySecurity,
		Description:         "IP reputation and abuse reporting database",
		BaseURL:             "https://api.abuseipdb.com/api/v2",
		AuthType:            AuthTypeAPIKeyHeader,
		AuthHeaderName:      "Key",
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"check_ip", "report_ip"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapHealthCheck},
		WebsiteURL:          "https://www.abuseipdb.com",
		DocsURL:             "https://docs.abuseipdb.com",
		APIReferenceURL:     "https://docs.abuseipdb.com",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier allows 1,000 checks per day.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "ipinfo",
		Name:                "IPinfo",
		Category:            CategorySecurity,
		Description:         "IP address geolocation and ASN intelligence",
		BaseURL:             "https://ipinfo.io",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"access_token"},
		SupportedOperations: []string{"lookup_ip"},
		Capabilities:        []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:          "https://ipinfo.io",
		DocsURL:             "https://ipinfo.io/developers",
		APIReferenceURL:     "https://ipinfo.io/developers",
		FreeTierStatus:      "available",
		FreeTierNotes:       "50,000 lookups per month free with token.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "generic-rest",
		Name:                "Generic REST API",
		Category:            CategoryCustom,
		Description:         "Custom user-defined HTTP REST endpoint with SSRF protection",
		BaseURL:             "",
		AuthType:            AuthTypeCustomHeader,
		RequiredCredentials: []string{"base_url"},
		SupportedOperations: []string{"get", "post", "put", "patch", "delete"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapBearerAuth, CapBasicAuth, CapRequestProxy, CapHealthCheck},
		WebsiteURL:          "https://ekarouter.dev",
		DocsURL:             "https://ekarouter.dev/docs/custom-providers",
		APIReferenceURL:     "https://ekarouter.dev/docs/custom-providers",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Self-configured.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "antigravity",
		Name:           "Antigravity",
		Category:       CategoryOAuth,
		Description:    "Google Cloud Code & Antigravity IDE models with OAuth",
		BaseURL:        "https://daily-cloudcode-pa.googleapis.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapQuotaAPI, CapHealthCheck, CapRequestProxy},
		WebsiteURL:     "https://antigravity.google",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "claude",
		Name:           "Claude Code",
		Category:       CategoryOAuth,
		Description:    "Anthropic Claude Code CLI with PKCE OAuth",
		BaseURL:        "https://api.anthropic.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck, CapRequestProxy},
		WebsiteURL:     "https://claude.ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "qoder",
		Name:           "Qoder",
		Category:       CategoryOAuth,
		Description:    "Qoder AI coding assistant OAuth connection",
		BaseURL:        "https://api.qoder.co",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://qoder.co",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "codex",
		Name:           "OpenAI Codex",
		Category:       CategoryOAuth,
		Description:    "OpenAI Codex CLI with PKCE OAuth flow",
		BaseURL:        "https://api.openai.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck, CapRequestProxy},
		WebsiteURL:     "https://openai.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "github-copilot",
		Name:           "GitHub Copilot",
		Category:       CategoryOAuth,
		Description:    "GitHub Copilot IDE & CLI OAuth integration",
		BaseURL:        "https://api.githubcopilot.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck, CapRequestProxy},
		WebsiteURL:     "https://github.com/features/copilot",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "cursor",
		Name:           "Cursor IDE",
		Category:       CategoryOAuth,
		Description:    "Cursor AI IDE connection and token mapping",
		BaseURL:        "https://api.cursor.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://cursor.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "kilocode",
		Name:           "Kilo Code",
		Category:       CategoryOAuth,
		Description:    "Kilo Code device authentication flow",
		BaseURL:        "https://api.kilocode.ai",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://kilocode.ai",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "cline",
		Name:           "Cline",
		Category:       CategoryOAuth,
		Description:    "Cline autonomous coding agent callback session",
		BaseURL:        "https://api.cline.bot",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://cline.bot",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "clinepass",
		Name:           "ClinePass",
		Category:       CategoryOAuth,
		Description:    "ClinePass shared authorization tunnel",
		BaseURL:        "https://api.clinepass.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://clinepass.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "codebuddy-intl",
		Name:           "CodeBuddy",
		Category:       CategoryOAuth,
		Description:    "CodeBuddy AI coding assistant",
		BaseURL:        "https://api.codebuddy.ai",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://codebuddy.ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "codebuddy-cn",
		Name:           "CodeBuddy CN",
		Category:       CategoryOAuth,
		Description:    "Tencent CodeBuddy Chinese region connection",
		BaseURL:        "https://api.codebuddy.cn",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://codebuddy.cn",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "kimi",
		Name:           "Kimi",
		Category:       CategoryOAuth,
		Description:    "Moonshot Kimi Code device authentication",
		BaseURL:        "https://api.kimi.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://kimi.moonshot.cn",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "grok-cli",
		Name:           "Grok CLI (Grok Build)",
		Category:       CategoryOAuth,
		Description:    "xAI Grok developer CLI authentication",
		BaseURL:        "https://api.x.ai",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://x.ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "xai",
		Name:           "xAI (Grok)",
		Category:       CategoryOAuth,
		Description:    "xAI Grok official API connection",
		BaseURL:        "https://api.x.ai/v1",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://x.ai",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "xiaomi-mimo",
		Name:           "Xiaomi MiMo",
		Category:       CategoryOAuth,
		Description:    "Xiaomi MiMo AI OAuth service",
		BaseURL:        "https://api.mimo.mi.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://mimo.mi.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "opencode",
		Name:           "OpenCode Free",
		Category:       CategoryFreeTier,
		Description:    "OpenCode free AI coding inference tier",
		BaseURL:        "https://opencode.ai",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://opencode.ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "gemini-cli",
		Name:           "Gemini CLI",
		Category:       CategoryFreeTier,
		Description:    "Google Gemini Cloud Companion CLI",
		BaseURL:        "https://cloudaicompanion.googleapis.com/v1",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapQuotaAPI, CapHealthCheck},
		WebsiteURL:     "https://ai.google.dev",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "kiro",
		Name:           "Kiro AI",
		Category:       CategoryFreeTier,
		Description:    "Kiro AI assistant free tier inference",
		BaseURL:        "https://kiro.ai",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://kiro.ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "openrouter",
		Name:           "OpenRouter",
		Category:       CategoryFreeTier,
		Description:    "Aggregated free tier and pay-as-you-go AI models",
		BaseURL:        "https://openrouter.ai/api/v1",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://openrouter.ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "nvidia",
		Name:           "NVIDIA NIM",
		Category:       CategoryFreeTier,
		Description:    "NVIDIA NIM Cloud inference microservices free tier",
		BaseURL:        "https://integrate.api.nvidia.com/v1",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://build.nvidia.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "ollama",
		Name:           "Ollama Cloud",
		Category:       CategoryFreeTier,
		Description:    "Local and cloud Ollama instances",
		BaseURL:        "http://localhost:11434",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://ollama.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "vertex",
		Name:           "Vertex AI",
		Category:       CategoryFreeTier,
		Description:    "Google Cloud Vertex AI studio",
		BaseURL:        "https://us-central1-aiplatform.googleapis.com",
		AuthType:       AuthTypeOAuth2,
		Capabilities:   []Capability{CapOAuth2, CapHealthCheck},
		WebsiteURL:     "https://cloud.google.com/vertex-ai",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "gemini",
		Name:           "Gemini",
		Category:       CategoryFreeTier,
		Description:    "Google AI Studio Gemini API free rate limits",
		BaseURL:        "https://generativelanguage.googleapis.com",
		AuthType:       AuthTypeAPIKeyHeader,
		Capabilities:   []Capability{CapAPIKeyAuth, CapHealthCheck},
		WebsiteURL:     "https://aistudio.google.com",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "poolside",
		Name:           "Poolside",
		Category:       CategoryFreeTier,
		Description:    "Poolside AI code foundation models",
		BaseURL:        "https://api.poolside.ai",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://poolside.ai",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "byteplus",
		Name:           "BytePlus ModelArk",
		Category:       CategoryFreeTier,
		Description:    "ByteDance BytePlus ModelArk models",
		BaseURL:        "https://ark.cn-beijing.volces.com",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://byteplus.com",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "kimchi",
		Name:           "Kimchi",
		Category:       CategoryFreeTier,
		Description:    "Kimchi free AI proxy and sandbox",
		BaseURL:        "https://api.kimchi.im",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://kimchi.im",
		FreeTierStatus: "available",
		Enabled:        true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "api-airforce",
		Name:           "API.airforce",
		Category:       CategoryFreeTier,
		Description:    "API Airforce community free tier models",
		BaseURL:        "https://api.airforce",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://api.airforce",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "bazaarlink",
		Name:           "Bazaarlink",
		Category:       CategoryFreeTier,
		Description:    "Bazaarlink decentralized inference provider",
		BaseURL:        "https://api.bazaarlink.com",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://bazaarlink.com",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:             "kilo-gateway",
		Name:           "Kilo Gateway",
		Category:       CategoryFreeTier,
		Description:    "Kilo Gateway AI model cluster",
		BaseURL:        "https://gateway.kilo.ai",
		AuthType:       AuthTypeBearerToken,
		Capabilities:   []Capability{CapBearerAuth, CapHealthCheck},
		WebsiteURL:     "https://kilo.ai",
		FreeTierStatus: "available",
		Enabled:        false,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "deepseek",
		Name:                "DeepSeek",
		Category:            CategoryAI,
		Description:         "DeepSeek official inference API featuring DeepSeek-V3 and DeepSeek-R1 reasoning models",
		BaseURL:             "https://api.deepseek.com",
		AuthType:            AuthTypeBearerToken,
		AuthHeaderName:      "Authorization",
		AuthHeaderPrefix:    "Bearer ",
		RequiredCredentials: []string{"api_key"},
		SupportedOperations: []string{"chat_completions", "models"},
		Capabilities:        []Capability{CapBearerAuth, CapRequestProxy, CapHealthCheck, CapStreaming},
		WebsiteURL:          "https://www.deepseek.com",
		DocsURL:             "https://api-docs.deepseek.com",
		APIReferenceURL:     "https://api-docs.deepseek.com",
		FreeTierStatus:      "available",
		FreeTierNotes:       "High performance, cost-effective reasoning and chat models.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "github-models",
		Name:                "GitHub Models",
		Category:            CategoryAI,
		Description:         "GitHub Models inference API — OpenAI-compatible endpoint with 30+ free models including GPT-4o, Llama 4, DeepSeek, Mistral, and Phi.",
		BaseURL:             "https://models.inference.ai.azure.com",
		AuthType:            AuthTypeBearerToken,
		AuthHeaderName:      "Authorization",
		AuthHeaderPrefix:    "Bearer ",
		RequiredCredentials: []string{"github_pat"},
		SupportedOperations: []string{"chat_completions", "models", "embeddings"},
		Capabilities:        []Capability{CapBearerAuth, CapRequestProxy, CapHealthCheck, CapStreaming},
		WebsiteURL:          "https://github.com/marketplace/models",
		DocsURL:             "https://docs.github.com/en/github-models",
		APIReferenceURL:     "https://docs.github.com/en/github-models/prototyping-with-ai-models",
		FreeTierStatus:      "available",
		FreeTierNotes:       "Free tier with rate-limited access via GitHub PAT — no credit card required.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "cloudinary",
		Name:                "Cloudinary",
		Category:            CategoryStorage,
		Description:         "Cloudinary media storage, transformation, and CDN delivery platform. Upload images and videos via REST API.",
		BaseURL:             "https://api.cloudinary.com/v1_1",
		AuthType:            AuthTypeBasicAuth,
		RequiredCredentials: []string{"api_key", "api_secret", "cloud_name"},
		SupportedOperations: []string{"upload", "list_resources", "delete_resource", "transform"},
		Capabilities:        []Capability{CapBasicAuth, CapFileUpload, CapFileDownload, CapHealthCheck, CapResourceListing},
		WebsiteURL:          "https://cloudinary.com",
		DocsURL:             "https://cloudinary.com/documentation/image_upload_api_reference",
		APIReferenceURL:     "https://cloudinary.com/documentation/image_upload_api_reference",
		FreeTierStatus:      "available",
		FreeTierNotes:       "25 credits/month free (~25 GB storage + transformations).",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "imagekit",
		Name:                "ImageKit",
		Category:            CategoryStorage,
		Description:         "ImageKit real-time image optimization, transformation, and global CDN. Store and serve media at scale.",
		BaseURL:             "https://api.imagekit.io/v1",
		AuthType:            AuthTypeBasicAuth,
		RequiredCredentials: []string{"private_key", "public_key", "url_endpoint"},
		SupportedOperations: []string{"upload", "list_files", "get_file", "delete_file", "purge_cache"},
		Capabilities:        []Capability{CapBasicAuth, CapFileUpload, CapFileDownload, CapHealthCheck, CapResourceListing},
		WebsiteURL:          "https://imagekit.io",
		DocsURL:             "https://docs.imagekit.io/api-reference/upload-file-api",
		APIReferenceURL:     "https://docs.imagekit.io/api-reference/upload-file-api",
		FreeTierStatus:      "available",
		FreeTierNotes:       "20 GB bandwidth + 20 GB media storage free per month.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "aws-s3",
		Name:                "Amazon S3",
		Category:            CategoryStorage,
		Description:         "Amazon Simple Storage Service — industry-standard object storage with global CDN via CloudFront.",
		BaseURL:             "https://s3.amazonaws.com",
		AuthType:            AuthTypeServiceAcct,
		RequiredCredentials: []string{"access_key_id", "secret_access_key", "region", "bucket"},
		SupportedOperations: []string{"put_object", "get_object", "delete_object", "list_objects", "presign_url"},
		Capabilities:        []Capability{CapServiceAccount, CapSignedRequest, CapFileUpload, CapFileDownload, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://aws.amazon.com/s3",
		DocsURL:             "https://docs.aws.amazon.com/s3/",
		APIReferenceURL:     "https://docs.aws.amazon.com/AmazonS3/latest/API/",
		FreeTierStatus:      "trial",
		FreeTierNotes:       "5 GB storage, 20K GET, 2K PUT requests free for 12 months.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "r2",
		Name:                "Cloudflare R2",
		Category:            CategoryStorage,
		Description:         "Cloudflare R2 S3-compatible object storage with zero egress fees and global CDN.",
		BaseURL:             "https://api.cloudflare.com/client/v4",
		AuthType:            AuthTypeAPIKeyHeader,
		AuthHeaderName:      "X-Auth-Email",
		RequiredCredentials: []string{"account_id", "access_key_id", "secret_access_key", "bucket"},
		SupportedOperations: []string{"put_object", "get_object", "delete_object", "list_objects", "presign_url"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapSignedRequest, CapFileUpload, CapFileDownload, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://developers.cloudflare.com/r2",
		DocsURL:             "https://developers.cloudflare.com/r2/api/s3/api/",
		APIReferenceURL:     "https://developers.cloudflare.com/r2/api/s3/api/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "10 GB storage, 1M Class A + 10M Class B ops free per month — zero egress fees.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "backblaze-b2",
		Name:                "Backblaze B2",
		Category:            CategoryStorage,
		Description:         "Backblaze B2 S3-compatible object storage with Cloudflare CDN partnership for zero-egress delivery.",
		BaseURL:             "https://api.backblazeb2.com/b2api/v3",
		AuthType:            AuthTypeAPIKeyHeader,
		AuthHeaderName:      "Authorization",
		RequiredCredentials: []string{"key_id", "application_key", "bucket"},
		SupportedOperations: []string{"b2_upload_file", "b2_download_file", "b2_list_file_names", "b2_delete_file_version"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapSignedRequest, CapFileUpload, CapFileDownload, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://www.backblaze.com/cloud-storage",
		DocsURL:             "https://www.backblaze.com/apidocs/introduction-to-the-s3-compatible-api",
		APIReferenceURL:     "https://www.backblaze.com/apidocs/",
		FreeTierStatus:      "available",
		FreeTierNotes:       "10 GB storage + 1 GB/day download free forever.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "bunny",
		Name:                "Bunny.net CDN",
		Category:            CategoryStorage,
		Description:         "Bunny.net edge storage and global CDN with pull/push zone support. Ultra-low cost with high performance.",
		BaseURL:             "https://storage.bunnycdn.com",
		AuthType:            AuthTypeAPIKeyHeader,
		AuthHeaderName:      "AccessKey",
		RequiredCredentials: []string{"api_key", "storage_zone_name"},
		SupportedOperations: []string{"upload_file", "download_file", "list_files", "delete_file"},
		Capabilities:        []Capability{CapAPIKeyAuth, CapFileUpload, CapFileDownload, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://bunny.net",
		DocsURL:             "https://docs.bunny.net/reference/storage-api",
		APIReferenceURL:     "https://docs.bunny.net/reference/storage-api",
		FreeTierStatus:      "trial",
		FreeTierNotes:       "14-day free trial with $1 credit.",
		Enabled:             true,
	}, defaultTimeout))

	_ = r.Register(NewBaseAdapter(ProviderMetadata{
		ID:                  "supabase-storage",
		Name:                "Supabase Storage",
		Category:            CategoryStorage,
		Description:         "Supabase Storage for files and media — S3-compatible with built-in CDN transformations.",
		BaseURL:             "https://api.supabase.com/v1",
		AuthType:            AuthTypeBearerToken,
		RequiredCredentials: []string{"project_url", "service_key"},
		SupportedOperations: []string{"upload", "download", "delete", "list", "create_signed_url"},
		Capabilities:        []Capability{CapBearerAuth, CapFileUpload, CapFileDownload, CapResourceListing, CapHealthCheck},
		WebsiteURL:          "https://supabase.com/storage",
		DocsURL:             "https://supabase.com/docs/guides/storage",
		APIReferenceURL:     "https://supabase.com/docs/reference/javascript/storage-createbucket",
		FreeTierStatus:      "available",
		FreeTierNotes:       "1 GB storage included in free Supabase project.",
		Enabled:             true,
	}, defaultTimeout))
}
